#!/bin/bash

# Calculate, and add to the fits file, the following times:

# LST -- Local Siderial Time
# JD  -- Julian Date
# MJD -- Modified Julian Date

#
function show_help
{
    echo "Usage: add_times [options] fits-file"
    echo "Options:"
    echo "   -h           show this help"
    echo "   -f           force overwriting of existing FITS keywords"
    echo "   -n arg       write to copy of input fle with arg appended to its name"
}

. ./keywords_are_present_in_file.sh
. ./output_file_name.sh
. ./set_keywords_in_fits_header.sh
. ./keyword_names.sh

#use only the packaged version of wcstools
#WCSTOOLS=wcstools-local/bin


while [[ $1 == -* ]]; do
    case "$1" in
      -h|--help|-\?) show_help; exit 0;;
      -f) force=1; shift;;
      -n) if (($# > 2)) && [[ $2 != -* ]]; then
            name_addition=$2; shift 2
          else 
            echo "-n requires an argument" 1>&2
            exit 1
          fi ;;
      --) shift; break;;
      -*) echo "invalid option: $1" 1>&2; show_help; exit 1;;
    esac
done

if [[ $# != 1 ]] 
then
    show_help
    exit 1
fi

file=$1

# check whether file currently contains keywords. If it
# does, halt unless -f option has been passed.

keywords="$lst_name $jd_name $mjd_name"
keywords_present=$(keywords_are_present_in_file $file $keywords )
if [[ ($keywords_present) && ! $force ]]
then
    echo "use option -f to force replacement of existing $keywords"
    exit 1;
fi

# 

outfile=$(output_file_name $file $name_extension)

if [[ $outfile != $file ]]; then cp $file $outfile; fi

dateobs=$(get_keyword_from_fits_header $file DATE-OBS)
timeobs=$(get_keyword_from_fits_header $file TIME-OBS)
#echo $dateobs
#echo $timeobs
if [[ !($dateobs == *?T?*) ]]; then echo "MOO"; datetime=${dateobs}T$timeobs; else
    datetime=$dateobs; fi

jd=$(./wcstools-local/bin/getdate fd2jd $datetime)
mjd=$(./wcstools-local/bin/getdate fd2mjd $datetime)
longitude=$(./wcstools-local/bin/getdate deg2ang $(get_keyword_from_fits_header $file $longitude_name))

if [[ !$longitude ]]; then
    echo "No longitude present in FITS file!"
    exit 1
fi

#echo $longitude 
#echo "-l $longitude ft2lst $datetime"

#lst=$(./wcstools-local/bin/getdate -h $longitude fd2lst $datetime)
lst=$(./wcstools-local/bin/getdate -t -l $longitude fd2lst $datetime)

#echo $lst $jd $mjd

set_keywords_in_fits_header $outfile $lst_name=$lst / "$lst_comment" $jd_name=$jd / "$jd_comment" $mjd_name=$mjd / "$mjd_comment"
