#!/bin/bash

filter_status_file=NEEDS_FILTER.txt
object_status_file=NEEDS_OBJECT.txt
light_frame_file=LIGHT_FILES.txt

function show_help
{
    echo "Sure wish I had time to write documentation!"
}

. ./get_keyword_from_fits_header.sh
. ./keywords_are_present_in_file.sh
. ./keyword_names.sh

while [[ $1 == -* ]]; do
    case "$1" in
      -h|--help|-\?) show_help; exit 0;;
      -t) if (($# > 2)) && [[ $2 != -* ]]; then
            image_types_too=$2; shift 2
          else 
            echo "-t requires an argument" 1>&2
            exit 1
          fi ;;
      -o) if (($# > 2)) && [[ $2 != -* ]]; then
            output_file=$2; shift 2
          else 
            echo "-t requires an argument" 1>&2
            exit 1
          fi ;;
      --) shift; break;;
      -*) echo "invalid option: $1" 1>&2; show_help; exit 1;;
    esac
done

if [[ $# != 1 ]] 
then
    show_help
    exit 1
fi

#set -x
dir_name=$1

fits_files=$dir_name/*.fit

# loop over files
# using a stupid indexed array instead of associative array because
# server doesn't have bash4.
i=0



bias_temp_file=$dir_name/.$$.bias.txt
dark_temp_file=$dir_name/.$$.dark.txt
flat_temp_file=$dir_name/.$$.flat.txt
light_temp_file=$dir_name/.$$.light.txt

#
# check for existing output files, and nuke if needed:
#
/bin/rm -f $dir_name/$light_frame_file $dir_name/$filter_status_file $dir_name/$object_status_file

# for each file get:
# image type
# status of telescope keyword
# status of ra/dec/object keywords
for file in $fits_files; do
    file_name=$( basename $file )
    telescope_set=$( keywords_are_present_in_file $file $telescope_name )
    object_present=$( keywords_are_present_in_file $file $object_name )
    ra_present=$( keywords_are_present_in_file $file $ra_name $feder_ra_name)
    dec_present=$( keywords_are_present_in_file $file $dec_name $feder_dec_name)
    if [[ $object_present || ( $ra_present && $dec_present ) ]]; then 
	object_info_present="Yes"
    fi 
    filter_present=$( keywords_are_present_in_file $file $filter_name )
    image_type=$( get_keyword_from_fits_header $file $image_type_name )
#    echo $file $i

    shopt -s nocasematch
    case $image_type in
	Light* ) echo $file_name LIGHT >> $light_temp_file; 
	    echo $file_name >> $dir_name/LIGHT_FILES.txt
	    isLight="yes"
	    haveLight="yes";;
	Dark* ) echo  $file_name DARK >> $dark_temp_file; haveDark="yes";;
	Bias* ) echo $file_name BIAS >> $bias_temp_file; haveBias="yes";;
	Flat* ) echo $file_name FLAT >> $flat_temp_file; isFlat="Yes"; haveFlat="yes";;
	* ) echo "Bad news, unknown image type."; exit 1;;
    esac 
    shopt -u nocasematch

    # don't need filter for bias/dark
    if [[ $isLight || $isFlat ]]; then
	 if [[ ! ${filter_present} ]]; then echo $file_name >> $dir_name/$filter_status_file; wrote_filter=1; fi
    fi

    #only need object information for light images
    if [[ $isLight ]]; then
	if [[ ! ${object_info_present} ]]; then echo $file_name >> $dir_name/$object_status_file; wrote_object=1; fi
    fi 
    isLight=
    isFlat=
    : $(( i++ ))
done

if [[ $image_types_too ]]; then
    image_types_too=$dir_name/$image_types_too
    if [[ -e $image_types_too ]]; then rm $image_types_too; fi
    if [[ $haveBias ]]; then cat $bias_temp_file > $image_types_too; fi
    if [[ $haveDark ]]; then cat $dark_temp_file >> $image_types_too; fi
    if [[ $haveFlat ]]; then cat $flat_temp_file >> $image_types_too; fi
    if [[ $haveLight ]]; then cat $light_temp_file >> $image_types_too; fi
    rm -f $bias_temp_file $dark_temp_file $flat_temp_file $light_temp_file
fi

    





