#!/bin/bash

# include function for turning underscores into colons.
. ./subcolon.sh
. ./output_file_name.sh  # computes output file name
. ./keywords_are_present_in_file.sh
. ./set_keywords_in_fits_header.sh
. ./keyword_names.sh

function show_help
{
    echo "Usage: lat_long [options] fits-file"
    echo "Options:"
    echo "   -h           show this help"
    echo "   -f           force overwriting of existing keywords"
    echo "   -n arg       write to copy of input fle with arg appended to its name"
}
# processes or sets latitude/longitude for Feder Observatory in FITS file
# after running FITS file will contain keywords LATITUDE and LONGITUD
# with appropriate values in sexagesimal.
#
# processing is ncessary to properly format latitude/longitude from
# value written by MaximDL.

#use only the packaged version of wcstools
WCSTOOLS=wcstools-local/bin

default_latitude="46:52:00"
default_longitude="96:27:12"


while [[ $1 == -* ]]; do
    case "$1" in
      -h|--help|-\?) show_help; exit 0;;
      -f) force=1; shift;;
      -n) if (($# > 2)) && [[ $2 != -* ]]; then
            name_addition=$2; shift 2
          else 
            echo "-n requires an argument" 1>&2
            exit 1
          fi ;;
      --) shift; break;;
      -*) echo "invalid option: $1" 1>&2; show_help; exit 1;;
    esac
done

if [[ $# != 1 ]] 
then
    show_help
    exit 1
fi

file=$1

# check whether file currently contains latitude/longitude. If it
# does, halt unless -f option has been passed.

keywords="$latitude_name $longitude_name"
keywords_present=$(keywords_are_present_in_file $file $keywords )
if [[ ($keywords_present) && ! $force ]]
then
    echo "use option -f to force replacement of existing $keywords"
    exit 1;
fi

# check whether file already contains SITELAT and SITELONG. If it
# does, those override the defaults.
sitelat=$(get_keyword_from_fits_header $file  SITELAT)
sitelong=$(get_keyword_from_fits_header $file SITELONG)
latitude=$(subcolon ${sitelat:-$default_latitude} )
longitude=$(subcolon ${sitelong:-$default_longitude} )

# check for bogus negative longitude for Feder:

if [[ $longitude = -$default_longitude ]]; then longitude=$default_longitude; fi

# We are ready to write

# add name_addition to file name before the extension if

outfile=$(output_file_name $file $name_extension)

if [[ $outfile != $file ]]; then cp $file $outfile; fi

set_keywords_in_fits_header $outfile $latitude_name=$latitude / "$latitude_comment"  $longitude_name=$longitude / "$longitude_comment"




