#!/bin/bash

dir=$1

# check for wcstools

if [[ ! -e wcstools-local ]]; then
    echo "You are screwed, man, no wcstools!"
    exit 1
fi

# build wcstools if necessary

./make_wcstools

# Make a manifest to aid in processing files
./file_status_summary -t Manifest $dir

fits_files=$dir/*.fit

foo=( $fits_files )
nfiles=${#foo[@]}
light_files=$(cat $dir/LIGHT_FILES.txt)

#set -x
i=0
for file in $fits_files; do
    echo "Processing file $i of $nfiles: $file"
    ./lat_long  $file
    ./add_times $file
    : $(( i++ ))
done

# Do any files need an object? If so, abort.
if [[ -e $dir/NEEDS_OBJECT.txt ]]; then 
    echo "ERROR: Fix the object information before trying to add ra/dec!"
    exit 1;
fi

for file in $light_files; do
    ./ra_dec $dir/$file 
    ./ha_airmass $dir/$file
done