#!/bin/bash

function show_help
{
    echo "Sure wish I had time to write documentation!"
}

while [[ $1 == -* ]]; do
    case "$1" in
      -h|--help|-\?) show_help; exit 0;;
      -f ) force="-f"; shift;;
      --) shift; break;;
      -*) echo "invalid option: $1" 1>&2; show_help; exit 1;;
    esac
done

if [[ $# != 1 ]] 
then
    show_help
    exit 1
fi

#set -x
dir=$1

# check for wcstools

if [[ ! -e wcstools-local ]]; then
    echo "You are screwed, man, no wcstools!"
    exit 1
fi

# build wcstools if necessary

./make_wcstools

# Make a manifest to aid in processing files
./file_status_summary -t Manifest $dir

fits_files=$dir/*.fit

foo=( $fits_files )
nfiles=${#foo[@]}
light_files=$(cat $dir/LIGHT_FILES.txt)

#set -x
i=0
for file in $fits_files; do
    echo "Processing file $(( i+1 )) of $nfiles: $file"
    ./lat_long  $force $file
    ./add_times $force $file
    : $(( i++ ))
done

# Do any files need an object? If so, abort.
if [[ -e $dir/NEEDS_OBJECT.txt ]]; then 
    echo "ERROR: Fix the object information before trying to add ra/dec!"
    exit 1;
fi

foo=( $light_files )
nfiles=${#foo[@]}
i=0
for file in $light_files; do
    echo "Processing file $(( i+1 )) of $nfiles: $file"
    ./ra_dec $force $dir/$file 
    ./ha_airmass $force $dir/$file
    : $(( i++ ))
done