#!/bin/bash


function show_help
{
    echo "Usage: ra_dec [options] fits-file"
    echo "Options:"
    echo "   -h           show this help"
    echo "   -f           force overwriting of existing FITS keywords"
    echo "   -n arg       write to copy of input fle with arg appended to its name"
}

. ./keywords_are_present_in_file.sh
. ./output_file_name.sh
. ./set_keywords_in_fits_header.sh
. ./keyword_names.sh

getdate=./wcstools-local/bin/getdate
simpos=./wcstools-local/bin/simpos

while [[ $1 == -* ]]; do
    case "$1" in
      -h|--help|-\?) show_help; exit 0;;
      -f) force=1; shift;;
      -n) if (($# > 2)) && [[ $2 != -* ]]; then
            name_addition=$2; shift 2
          else 
            echo "-n requires an argument" 1>&2
            exit 1
          fi ;;
      --) shift; break;;
      -*) echo "invalid option: $1" 1>&2; show_help; exit 1;;
    esac
done

if [[ $# != 1 ]] 
then
    show_help
    exit 1
fi

file=$1

keywords="$ra_name $dec_name"
keywords_present=$(keywords_are_present_in_file $file $keywords )
if [[ ($keywords_present) && ! $force ]]
then
    echo "use option -f to force replacement of existing $keywords"
    exit 1;
fi
outfile=$(output_file_name $file $name_extension)

if [[ $outfile != $file ]]; then cp $file $outfile; fi

objectra=$(get_keyword_from_fits_header $file OBJCTRA)
objectdec=$(get_keyword_from_fits_header $file OBJCTDEC)
object=$(get_keyword_from_fits_header $file OBJECT)
if [[ $objectdec && $objectra ]]; then    
    ra=$(subcolon $objectra)
    dec=$(subcolon $objectdec)
    equinox="2000.0"
elif [[ $object ]]; then
    simbad=($($simpos $object))
    if [[ ! $simbad ]]; then
	 echo "Not found"
	 exit 1;
    elif [[ $simbad == [0-9]* ]]; then
	echo ${#simbad}
	ra=${simbad[0]}
	dec=${simbad[1]}
	equinox="2000.0"
    fi 
else 
    echo "RA/Dec and Object Name are all missing from FITS file."
    exit 1
fi

# if we made it this far we are ready to write.
set_keywords_in_fits_header $outfile $ra_name=$ra / "$ra_comment" $dec_name=$dec / "$dec_comment" $equinox_name=$equinox / "$equinox_comment"